const assert = require('assert');
const G = require('./scoring');
const round = () => ({scores: Array.from({length:4},()=>Array(18).fill(null)),teamScores:Array.from({length:2},()=>Array(18).fill(null)),pars:Array(18).fill(4),indexes:Array.from({length:18},(_,i)=>i+1)});
assert.equal(G.strokes(20,1),2);
assert.equal(G.strokes(20,3),1);
assert.equal(G.strokes(-2,18),-1);
assert.equal(G.strokes(-2,1),0);
assert.deepEqual(G.hole(5,4,1,18),{gross:5,net:4,points:2});
assert.equal(G.hole(12,4,1,0).points,0);
assert.equal(G.hole(null,4,1,18),null);
assert.deepEqual(G.placingPoints([20,20,18,15]),[3.5,3.5,2,1]);
assert.deepEqual(G.placingPoints([0,0,0,0]),[2.5,2.5,2.5,2.5]);
let r=round();
r.scores[0][0]=3;r.scores[1][0]=4;r.scores[2][0]=5;
assert.deepEqual(G.competition(r,[0,0,0,0],[[0,3],[2,1]],'match'),{totals:[0,0],holes:0});
r.scores[3][0]=4;
assert.deepEqual(G.competition(r,[0,0,0,0],[[0,3],[2,1]],'match'),{totals:[1,0],holes:1});
assert.deepEqual(G.competition(r,[0,0,0,0],[[1,3],[2,0]],'best'),{totals:[2,3],holes:1});
assert.equal(G.totals(r,0,0).points,3);
assert.equal(G.totals(r,0,18).points,4);
r.teamScores[0][0]=3;r.teamScores[1][0]=4;r.teamScores[0][1]=5;
assert.deepEqual(G.competition(r,[20,0,0,0],[[3,2],[0,1]],'scramble'),{totals:[3,4],holes:1});
assert.equal(G.played(0),false);
assert.equal(G.played(3.5),false);
console.log('All scoring tests passed: stroke allocation, Stableford, ties, handicap updates, teams and incomplete holes.');
const fs = require('fs');
const vm = require('vm');
const app = { innerHTML:'', addEventListener(){} };
const mobileEvents = {};
const context = vm.createContext({ Golf:G, document:{getElementById:()=>app,addEventListener:(type,handler)=>mobileEvents[type]=handler}, localStorage:{getItem:()=>null,setItem(){}}, location:{hash:''}, window:{addEventListener(){},scrollTo(){}}, console });
vm.runInContext('const Live={save(){updateRankMovement();},access(){}};',context);
vm.runInContext(fs.readFileSync('courses.js','utf8'),context);
vm.runInContext(fs.readFileSync('mobile.js','utf8'),context);
vm.runInContext(fs.readFileSync('app.js','utf8'),context);
for (const view of ['dashboard','scorecard','players','rules']) {
  vm.runInContext(`page='${view}';render()`,context);
  assert(app.innerHTML.includes('<main>'));
  assert(!app.innerHTML.includes('NaN'));
}
vm.runInContext(`data.rounds[0].scores.forEach((s,p)=>s[0]=p+3);`,context);
assert.equal(vm.runInContext('overall()[0].points',context),4);
vm.runInContext('data.handicaps[3]=54;',context);
assert.equal(vm.runInContext('overall()[0].points',context),3.5);
vm.runInContext('data.rounds[3].ctp=3;',context);
assert.equal(vm.runInContext('overall()[0].p',context),3);
assert.equal(vm.runInContext('overall()[0].points',context),4.5);
assert.equal(vm.runInContext('valid(data)',context),true);
vm.runInContext('selected=3;scorecard()',context);
assert(app.innerHTML.includes('Owen &amp; Mark') || app.innerHTML.includes('Owen & Mark'));
console.log('Page rendering and overall standings checks passed.');
vm.runInContext('data=empty();selected=0;',context);
assert.equal(vm.runInContext('firstUnfinishedHole(0)',context),0);
vm.runInContext('data.rounds[0].scores.forEach(s=>s[0]=4);',context);
assert.equal(vm.runInContext('firstUnfinishedHole(0)',context),1);
assert.equal(vm.runInContext('steppedScore(null,1,5)',context),5);
assert.equal(vm.runInContext('steppedScore(1,-1,4)',context),1);
assert.equal(vm.runInContext('steppedScore(30,1,4)',context),30);
let mobileHTML=vm.runInContext('mobileHoleEditor()',context);
assert.equal((mobileHTML.match(/data-mobile-score=/g)||[]).length,4);
assert(mobileHTML.includes('Hole 2'));
vm.runInContext('selected=3;',context);
mobileHTML=vm.runInContext('mobileHoleEditor()',context);
assert.equal((mobileHTML.match(/data-mobile-score=/g)||[]).length,2);
assert(mobileHTML.includes('Owen & Mark'));
assert(mobileHTML.includes('James & Ben'));
vm.runInContext('data.rounds[3].teamScores.forEach(s=>s.fill(4));',context);
assert.equal(vm.runInContext('firstUnfinishedHole(3)',context),17);
vm.runInContext('mobileHoles[3]=17;',context);
assert(vm.runInContext('mobileHoleEditor()',context).includes('View standings'));
// Exercise the real touch input handler: invalid input must not replace saved data.
const result={textContent:''}, commits=[];
app.querySelector=()=>result;
context.captureCommit=(p,value)=>commits.push([p,value]);
vm.runInContext('commitMobileScore=captureCommit;',context);
const input={dataset:{mobileScore:'1'},validity:{badInput:false},value:'5',setCustomValidity(message){this.message=message;},setAttribute(){}};
mobileEvents.input({target:input});
assert.deepEqual(commits,[[1,5]]);
input.value='3.5';mobileEvents.input({target:input});
assert.equal(commits.length,1);
assert(input.message.includes('whole score'));
input.value='';mobileEvents.input({target:input});
assert.deepEqual(commits[1],[1,null]);
console.log('Mobile checks passed: resume hole, score limits, player/team entry, completion and input validation.');
// Prize pots must total £200, with no early awards or arbitrary tie payouts.
const teams=[[[0,3],[2,1]],[[1,3],[2,0]],[],[[3,2],[0,1]]];
const formats=['match','best','solo','scramble'];
const rounds=Array.from({length:4},()=>({...round(),verified:true,ctp:0}));
const standings=[{p:0,points:16},{p:1,points:9},{p:2,points:6},{p:3,points:3}];
const blank=rounds.map(r=>({...r,ctp:null}));
assert.equal(G.earnings(blank,[0,0,0,0],teams,formats,standings).players.reduce((sum,p)=>sum+p.earned+p.projected,0),0);
rounds.slice(0,3).forEach((r,i)=>r.scores.forEach((s,p)=>s.fill(i===0 && p===0 ? 2 : p+3)));
rounds[3].teamScores[0].fill(3);rounds[3].teamScores[1].fill(4);
let prizes=G.earnings(rounds,[0,0,0,0],teams,formats,standings);
assert.deepEqual(prizes.players.map(p=>p.earned),[100,20,40,40]);
assert.equal(prizes.players.reduce((sum,p)=>sum+p.earned,0),200);
assert.equal(prizes.tiedPrizes,0);
rounds[3].ctp=null;
prizes=G.earnings(rounds,[0,0,0,0],teams,formats,standings);
assert.equal(prizes.players[0].earned,60);
assert.equal(prizes.players[0].projected,40);
rounds[0].verified=false;
prizes=G.earnings(rounds,[0,0,0,0],teams,formats,standings);
assert.equal(prizes.players[0].earned,40);
assert.equal(prizes.players[0].projected,60);
rounds[3].teamScores[1].fill(3);
prizes=G.earnings(rounds,[0,0,0,0],teams,formats,standings.map(p=>({...p,points:10})));
assert.equal(prizes.tiedPrizes,100); // £40 scramble and £60 overall.
assert.equal(prizes.players[1].earned+prizes.players[1].projected,0);
delete app.querySelector;
vm.runInContext('data=empty();page="dashboard";render();',context);
assert(app.innerHTML.includes('PRIZE MONEY WON'));
assert(app.innerHTML.includes('Earnings are prize money before'));
assert(app.innerHTML.includes('£0'));
console.log('Earnings checks passed: £200 pot, pending bonuses, unverified courses, ties and leaderboard rendering.');
vm.runInContext('data=empty();updateRankMovement();',context);
assert.equal(vm.runInContext('previousRanks',context),null);
vm.runInContext('data.rounds[0].scores.forEach((s,p)=>s[0]=p+3);save();',context);
assert.equal(vm.runInContext('rankMovement.join(",")',context),'0,0,0,0');
assert.equal(vm.runInContext('overall().map(r=>r.p).join(",")',context),'0,1,2,3');
vm.runInContext('data.handicaps[3]=54;save();',context);
assert.equal(vm.runInContext('rankMovement.join(",")',context),'0,-1,-1,3');
assert.equal(vm.runInContext('overall().map(r=>r.p).join(",")',context),'0,3,1,2');
assert(vm.runInContext('movementMarkup(3)',context).includes('rank-up'));
assert(vm.runInContext('movementMarkup(1)',context).includes('rank-down'));
vm.runInContext('render();save();',context);
assert.equal(vm.runInContext('rankMovement[3]',context),3); // Navigation/no-op save preserves last movement.
vm.runInContext('data.rounds[3].ctp=3;save();',context);
assert.equal(vm.runInContext('overall()[0].p',context),3);
assert.equal(vm.runInContext('rankMovement.join(",")',context),'-1,0,0,0');
vm.runInContext('data=empty();save();',context);
assert.equal(vm.runInContext('rankMovement.join(",")',context),'0,0,0,0');
console.log('Leaderboard checks passed: automatic ordering, shared ranks, up/down movement, bonuses and reset.');
context.seedCourses=JSON.parse(fs.readFileSync('course_defaults.json','utf8'));
vm.runInContext('data=empty();courseLibrary=seedCourses;data.rounds[0].scores[0][0]=6;data.handicaps[0]=18;data.rounds[0].ctp=0;applyTee(0,courseLibrary[0].tees[0]);',context);
assert.equal(vm.runInContext('data.rounds[0].scores[0][0]',context),6);
assert.equal(vm.runInContext('data.handicaps[0]',context),18);
assert.equal(vm.runInContext('data.rounds[0].ctp',context),null);
assert.equal(vm.runInContext('data.rounds[0].pars.lastIndexOf(3)',context),16);
assert.equal(vm.runInContext('teeDistance(0,0)',context),'428 m');
assert.equal(vm.runInContext('Golf.totals(data.rounds[0],0,18).points',context),2);
assert.equal(vm.runInContext('valid(data)',context),true);
vm.runInContext('data.rounds[0].ctp=1;applyTee(0,courseLibrary[0].tees[1]);',context);
assert.equal(vm.runInContext('teeDistance(0,0)',context),'418 m');
assert.equal(vm.runInContext('data.rounds[0].ctp',context),1);
assert.equal(vm.runInContext('teeSnapshotValid({id:"x",name:"x",unit:"m",distances:[1]})',context),false);
assert(vm.runInContext('courseSelection(0)',context).includes('5,350'));
assert(vm.runInContext('courseLibrarySetup(0)',context).includes('data-course-upload="map"'));
assert(vm.runInContext('escapeHTML("<script>")',context).includes('&lt;script&gt;'));
console.log('Course checks passed: tee selection, preserved scores/handicaps, correct pin hole, distances and backup validation.');
